# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=255, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=255, null=True)),
                ('gest', models.CharField(blank=True, max_length=255, null=True)),
                ('examp', models.CharField(blank=True, max_length=255, null=True)),
                ('constr', models.CharField(blank=True, max_length=255, null=True)),
                ('trans', models.CharField(blank=True, max_length=255, null=True)),
                ('comm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'LanguagesData',
            },
        ),
    ]
